// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeeklyBudget.Data;

#nullable disable

namespace WeeklyBudget.Migrations
{
    [DbContext(typeof(WeeklyBudgetContext))]
    [Migration("20230710150636_initialxx")]
    partial class initialxx
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WeeklyBudget.Models.Budget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BudgetId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BudgetDate")
                        .HasColumnType("date");

                    b.Property<decimal>("TotalBudget")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Budgets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BudgetDate = new DateTime(2023, 7, 10, 17, 6, 36, 526, DateTimeKind.Local).AddTicks(1021),
                            TotalBudget = 18000.0m
                        },
                        new
                        {
                            Id = 2,
                            BudgetDate = new DateTime(2023, 7, 10, 17, 6, 36, 526, DateTimeKind.Local).AddTicks(1069),
                            TotalBudget = 12000.0m
                        });
                });

            modelBuilder.Entity("WeeklyBudget.Models.BudgetDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BudgetDetailId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BudgetId")
                        .HasColumnType("int");

                    b.Property<int?>("ExpenditureTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalBudget")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BudgetId");

                    b.HasIndex("ExpenditureTypeId");

                    b.ToTable("BudgetDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BudgetId = 1,
                            ExpenditureTypeId = 1,
                            TotalBudget = 2000.0m
                        },
                        new
                        {
                            Id = 2,
                            BudgetId = 1,
                            ExpenditureTypeId = 2,
                            TotalBudget = 2000.0m
                        },
                        new
                        {
                            Id = 3,
                            BudgetId = 1,
                            ExpenditureTypeId = 3,
                            TotalBudget = 4000.0m
                        },
                        new
                        {
                            Id = 4,
                            BudgetId = 2,
                            ExpenditureTypeId = 1,
                            TotalBudget = 3000.0m
                        },
                        new
                        {
                            Id = 5,
                            BudgetId = 2,
                            ExpenditureTypeId = 2,
                            TotalBudget = 2500.0m
                        },
                        new
                        {
                            Id = 6,
                            BudgetId = 2,
                            ExpenditureTypeId = 3,
                            TotalBudget = 5000.0m
                        });
                });

            modelBuilder.Entity("WeeklyBudget.Models.Expenditure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ExpenditureId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BudgetId")
                        .HasColumnType("int");

                    b.Property<int>("ExpenditureTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("SpentAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("SpentDate")
                        .HasColumnType("date");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BudgetId");

                    b.ToTable("Expenditures");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BudgetId = 1,
                            ExpenditureTypeId = 1,
                            SpentAmount = 1000.0m,
                            SpentDate = new DateTime(2023, 7, 10, 17, 6, 36, 526, DateTimeKind.Local).AddTicks(1882),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            BudgetId = 1,
                            ExpenditureTypeId = 2,
                            SpentAmount = 2000.0m,
                            SpentDate = new DateTime(2023, 7, 10, 17, 6, 36, 526, DateTimeKind.Local).AddTicks(1886),
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            BudgetId = 1,
                            ExpenditureTypeId = 1,
                            SpentAmount = 3000.0m,
                            SpentDate = new DateTime(2023, 7, 10, 17, 6, 36, 526, DateTimeKind.Local).AddTicks(1889),
                            UserId = 2
                        },
                        new
                        {
                            Id = 10,
                            BudgetId = 1,
                            ExpenditureTypeId = 1,
                            SpentAmount = 100.0m,
                            SpentDate = new DateTime(2023, 7, 10, 17, 6, 36, 526, DateTimeKind.Local).AddTicks(1892),
                            UserId = 1
                        },
                        new
                        {
                            Id = 11,
                            BudgetId = 1,
                            ExpenditureTypeId = 3,
                            SpentAmount = 400.0m,
                            SpentDate = new DateTime(2023, 7, 10, 17, 6, 36, 526, DateTimeKind.Local).AddTicks(1895),
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            BudgetId = 2,
                            ExpenditureTypeId = 0,
                            SpentAmount = 1000.0m,
                            SpentDate = new DateTime(2023, 7, 10, 17, 6, 36, 526, DateTimeKind.Local).AddTicks(1898),
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            BudgetId = 2,
                            ExpenditureTypeId = 3,
                            SpentAmount = 2000.0m,
                            SpentDate = new DateTime(2023, 7, 10, 17, 6, 36, 526, DateTimeKind.Local).AddTicks(1901),
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            BudgetId = 2,
                            ExpenditureTypeId = 3,
                            SpentAmount = 3000.0m,
                            SpentDate = new DateTime(2023, 7, 10, 17, 6, 36, 526, DateTimeKind.Local).AddTicks(1904),
                            UserId = 2
                        },
                        new
                        {
                            Id = 7,
                            BudgetId = 2,
                            ExpenditureTypeId = 2,
                            SpentAmount = 1000.0m,
                            SpentDate = new DateTime(2023, 7, 10, 17, 6, 36, 526, DateTimeKind.Local).AddTicks(1907),
                            UserId = 2
                        },
                        new
                        {
                            Id = 8,
                            BudgetId = 2,
                            ExpenditureTypeId = 2,
                            SpentAmount = 100.0m,
                            SpentDate = new DateTime(2023, 7, 10, 17, 6, 36, 526, DateTimeKind.Local).AddTicks(1909),
                            UserId = 2
                        },
                        new
                        {
                            Id = 9,
                            BudgetId = 2,
                            ExpenditureTypeId = 1,
                            SpentAmount = 150.0m,
                            SpentDate = new DateTime(2023, 7, 10, 17, 6, 36, 526, DateTimeKind.Local).AddTicks(1912),
                            UserId = 2
                        });
                });

            modelBuilder.Entity("WeeklyBudget.Models.ExpenditureType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ExpenditureTypeId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ExpenditureTypeName");

                    b.HasKey("Id");

                    b.ToTable("ExpenditureTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Sex"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Drogy"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Alcohol"
                        });
                });

            modelBuilder.Entity("WeeklyBudget.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("UserName");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pepa"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Růžena"
                        });
                });

            modelBuilder.Entity("WeeklyBudget.Models.BudgetDetail", b =>
                {
                    b.HasOne("WeeklyBudget.Models.Budget", "Budget")
                        .WithMany("BudgetDetails")
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WeeklyBudget.Models.ExpenditureType", "ExpenditureType")
                        .WithMany()
                        .HasForeignKey("ExpenditureTypeId");

                    b.Navigation("Budget");

                    b.Navigation("ExpenditureType");
                });

            modelBuilder.Entity("WeeklyBudget.Models.Expenditure", b =>
                {
                    b.HasOne("WeeklyBudget.Models.Budget", "Budget")
                        .WithMany("Expenditures")
                        .HasForeignKey("BudgetId");

                    b.Navigation("Budget");
                });

            modelBuilder.Entity("WeeklyBudget.Models.Budget", b =>
                {
                    b.Navigation("BudgetDetails");

                    b.Navigation("Expenditures");
                });
#pragma warning restore 612, 618
        }
    }
}
