// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeeklyBudget.Data;

#nullable disable

namespace WeeklyBudget.Migrations
{
    [DbContext(typeof(WeeklyBudgetContext))]
    partial class WeeklyBudgetContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WeeklyBudget.Models.Budget", b =>
                {
                    b.Property<int>("BudgetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BudgetId"));

                    b.Property<DateTime>("BudgetDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalBudget")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("BudgetId");

                    b.ToTable("Budgets");
                });

            modelBuilder.Entity("WeeklyBudget.Models.BudgetDetail", b =>
                {
                    b.Property<int>("BudgetDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BudgetDetailId"));

                    b.Property<int>("BudgetId")
                        .HasColumnType("int");

                    b.Property<int>("ExpenditureTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalBudget")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("BudgetDetailId");

                    b.HasIndex("BudgetId");

                    b.HasIndex("ExpenditureTypeId");

                    b.ToTable("BudgetDetails");
                });

            modelBuilder.Entity("WeeklyBudget.Models.Expenditure", b =>
                {
                    b.Property<int>("ExpenditureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExpenditureId"));

                    b.Property<int>("ExpenditureTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("SpentAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("SpentDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ExpenditureId");

                    b.HasIndex("ExpenditureTypeId");

                    b.ToTable("Expenditures");
                });

            modelBuilder.Entity("WeeklyBudget.Models.ExpenditureType", b =>
                {
                    b.Property<int>("ExpenditureTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExpenditureTypeId"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ExpenditureTypeId");

                    b.ToTable("ExpenditureTypes");
                });

            modelBuilder.Entity("WeeklyBudget.Models.BudgetDetail", b =>
                {
                    b.HasOne("WeeklyBudget.Models.Budget", "Budget")
                        .WithMany("BudgetDetails")
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WeeklyBudget.Models.ExpenditureType", null)
                        .WithMany()
                        .HasForeignKey("ExpenditureTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Budget");
                });

            modelBuilder.Entity("WeeklyBudget.Models.Expenditure", b =>
                {
                    b.HasOne("WeeklyBudget.Models.ExpenditureType", null)
                        .WithMany()
                        .HasForeignKey("ExpenditureTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WeeklyBudget.Models.Budget", b =>
                {
                    b.Navigation("BudgetDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
